Fix --without-tcp-wrappers unused-but-set-variable
This commit fixes an unused-but-set-variable warning with gcc 6.2.0
on Ubuntu 16.10 that occurs when configured "--without-tcp-wrappers":

> server-sock.c: In function 'resolve_addr':
> server-sock.c:169:9: error: variable 'gotHostName' set but not used
>       [-Werror=unused-but-set-variable]
>      int gotHostName = 0;
>          ^~~~~~~~~~~

Instead of using the gcc compiler "unused" attribute (i.e.,
"__attribute__((__unused__))"), this opts for a hopefully more portable
approach by casting to void.

Signed-off-by: Chris Dunlap <cdunlap@llnl.gov>