Travis: Add configure --with-freeipmi
Add the configure --with-freeipmi option to test builds having support
for FreeIPMI's Serial-Over-LAN (libipmiconsole).  This requires the
installation of the libfreeipmi-dev and libipmiconsole-dev packages
in Ubuntu.

While the build succeeds, "make distcheck" fails with:

  ERROR: files left in build directory after distclean:
  ./.deps/server-ipmi.Po

Failed:
- Ubuntu 20.04.1 LTS