Fix distcheck err from leftover server-ipmi.Po
When configured with the option "--with-freeipmi", "make distcheck"
fails with the following error:

  ERROR: files left in build directory after distclean:
  ./.deps/server-ipmi.Po

"make" produces "server-ipmi.o" and ".deps/server-ipmi.Po" along
with a dummy "conmand-server-ipmi.Po" (i.e., containing a single line
"# dummy").

"Makefile.am" defines EXTRA_conmand_SOURCES = "server-ipmi.c".

"Makefile.in" contains a rule for "conmand-server-ipmi.o" referencing
"$(DEPDIR)/conmand-server-ipmi.Po", but not a rule for "server-ipmi.o".

"m4/x_ac_with_freeipmi.m4" uses AC_SUBST to set FREEIPMIOBJS to
"server-ipmi.$(OBJEXT)".  Note the missing "conmand-" prefix!
Changing the AC_SUBST to "conmand-server-ipmi.$(OBJEXT)"
results in "make" correctly producing "conmand-server-ipmi.o" and
".deps/conmand-server-ipmi.Po", and "make distclean" cleaning-up
as expected.  Likewise, "make distcheck" now succeeds.

Tested:
- CentOS Stream, 8.2.2004, 7.8.2003
- Debian sid, 10.6, 9.13, 8.11, 7.11
- Fedora 32, 31, 30
- openSUSE 15.2, 15.1
- Ubuntu 20.04.1 LTS, 18.04.5 LTS, 16.04.7 LTS, 14.04.6 LTS