conmand: Fix error message for invalid port
If the "-p" command-line option (for specifying the listening port)
is given a non-integer argument, the following error message is output:

  ERROR:     CMDLINE: invalid port "0"

Fix the error message by printing "optarg" instead of the invalid
result from atoi().